#!/bin/bash 
# Enhanced filtering from docker images with grep

#set -x

usage(){
   			echo " "
   			echo " "
   			echo "Enhanced docker images filtering"
   			echo " "
   			echo " "

   			echo "Usage:   $0 spring  -Filters results with grep on arg"
   			echo " "
   			echo " "
   			echo " "
	exit 1
}   

	theCommand="docker images "

	if [ $# -gt 0 ]
		then			

      for argz in "$@"
      do
        
        theCommand+=" |grep $argz "

      done

	fi

  #echo "theCommand Be: $theCommand" 

  eval "$theCommand"
