#!/bin/bash
#
# Backup a centralized version of calm-dsl configs.  Contains files deployed to both UBU or MAC.
# Its calm, sooo, it should be same right?  Except for target folders..
#

#set -x

	usage(){
	   			echo " "
	   			echo " "
	   			echo " "
	   			echo "Usage:   $0 -F/-f 			-Force back-up to LAN if VPN Connection Detected."
	   			echo "            -H/-h				-Show this help Screen."
	   			echo " "
	   			echo " "
		exit 1
	}

		if [  "$1" == "-H" ] || [ "$1" == "-h" ]
	  		then
					usage
	  fi
	  
	  #
	  # Used to differentiate if this is running on a Company-MAC or just a 'Nix box
	  #

	  unamestr=$(uname)

		if [ "$unamestr" = 'Darwin' ] 
			then
			
				# MAC-os Impl:
	  		baseFolderRoot="/Users/eric.manley"
	
		else 

			# Linux Impl:
			  baseFolderRoot=""
		fi	


		HomeSRCDir=""
		HomeSRCDir="$baseFolderRoot/data/yaml/NKP/calm/configs"

		MaxFolders=''
		MaxFolders='20'

    ParentDirName=""
    ParentDirName="$baseFolderRoot/data/back/$HOSTNAME/data/yaml/NKP/calm/configs"

		ChildDirName=''
		ChildDirName='central-calm-configs'

    export LAN_VOL=
    export LAN_VOL='/media/eric/SlaveB'
    #export LAN_VOL='/Users/eric.manley/OneDrive/OneDrive - Nutanix/$HOSTNAME/Users/eric.manley'    

		LANParentDirName=""
		LANParentDirName="$LAN_VOL$ParentDirName"

		needleHome="192.168.1"

		ifconfig | grep $needleHome >/dev/null
		greprc=$?

	  cd $HomeSRCDir


		#	  
	  # See if this is a maven project...if so run clean.  No need to backup build-files..Otherwise press-on.
	  #
	  
		thePomFile="./pom.xml"
		
		if [[ -f "$thePomFile" ]]; then
		    echo " "
		    echo "Maven POM.XML Detected...running clean..."
		    echo " "

				m3 clean
		fi	  

		# Backs up locally to shadow directory...

		"$baseFolderRoot"/dev2/sh/cycleFolders2 "$ParentDirName" "$ChildDirName" "$MaxFolders"

		mkdir "$ParentDirName"
		mkdir "$ParentDirName/$ChildDirName"

		# Need a call to mvn clean here..

		"$baseFolderRoot"/dev2/sh/syncBackDir3  "$ParentDirName/$ChildDirName" "$HomeSRCDir" '**/*' '**/.git/*'

		# Backs up locally to external storage

		#
		# Check to see if at home...FORCE flag must be present, otherwise do LAN backup....
		#

		if [ $greprc -eq 0 ]
		   then

	        echo " "
	     		echo "*** Running At Home, Checking for FORCE..."
	        echo " "

					if [  "$1" == "-F" ] || [ "$1" == "-f" ]
	  				 then
								echo " "
								echo "FORCE DETECTED....Using FORCE!!"
								echo " "
				  else
 								echo " "
								echo "NO FORCE DETECTED....Dropping out..."
								echo " "

				  	 		exit 0
					fi

		fi

		# Does this exist ?
	 	if [ -d "$LAN_VOL" ]
				then

					"$baseFolderRoot"/dev2/sh/cycleFolders2 "$LANParentDirName" "$ChildDirName" "$MaxFolders"

					mkdir "$LANParentDirName"
					mkdir "$LANParentDirName/$ChildDirName"

					"$baseFolderRoot"/dev2/sh/syncBackDir3  "$LANParentDirName/$ChildDirName" "$HomeSRCDir" '**/*' '**/.git/*'


		else
				echo "$LAN_VOL" is not attached!
		fi
