#!/bin/bash 
# Process backup files locally, in order of:  CycleLocal, BackItUp, YankStuff.....



#  set -x

usage(){
   			echo " "
   			echo " "
			  echo "Usage $0 [Directory, FileNameSeed, MaxFiles, FileNameSuffix, (ie .ZIP)]"   
   			echo " "                                                                     
   			echo " "
   			echo "  Example: $0 /data/back fileTest 10 .tar"
   			echo " "
	exit 1
}   
  
	if [ $# -lt 4 ] 
		then
			usage
			exit 1
	fi

	export MAXFILES=
	export MAXFILES=$3

	#
	# Hammer the last file	
	#
	
	rm "$1$2$3$4"
	
	
	#
	# Now step thru from the ending renaming each one to +1 from what it was.
	#
	
	x=$MAXFILES
	while [ $x -ge 1 ]
	do
  		
  		y=$(( $x - 1 ))  		
  		
			mv $1$2$y$4 $1$2$x$4
  		
  		x=$(( $x - 1 ))
	done	
	

	#
	# Now, rename last file to first seed which is 1 ....
	#      
	mv $1$2$4 $1/$2'1'$4
	
