#!/bin/bash
#  Call gradle's dependency list with recursive grep's
#

#set -x

usage(){
        echo " "
        echo " "
        echo "Enhanced gradle dependancies filtering"
        echo " "
        echo " "

        echo "Usage:   $0 x,y,z  -RECURSIVELY Filters results with grep based on args provided."
        echo " "
        echo " "
        echo " "
  exit 1
}   

case $1 in

    -help)
        usage
        ;;
    --help)
        usage
        ;;

    -h)
        usage
        ;;
        
    -H)
        usage
        ;;

    --h)
        usage
        ;;
        
    --H)
        usage
        ;;

esac  

theCommand="g dependencies "


if [ $# -gt 0 ]
  then      

    for argz in "$@"
    do
      
      theCommand+=" |grep $argz "

    done

fi

echo "theCommand Be: $theCommand" 

eval "$theCommand"


