#!/bin/bash
#  Script that graps a certain eVar places it on clipboard.
#

#set -x

usage(){
   			echo " "
   			echo " "
   			echo " "
   			echo "Usage:   $0 enviro resource"
   			echo " "
   			echo " "
   			echo " Ex:  getit gpu k			# loads clipboard with gpu-enviro k-creds"
   			echo " "
   			echo " "
   			echo " "   			
   			echo " "
	exit 1
}


   	if [ $# -lt 2 ]
   		then
				usage
   	fi
		
		enviro=''
		evalue=''
		returnValue=''
		 
		if [  "$1" == "gpu" ]
	  		then
	  		
					if [  "$2" == "k" ]
				  		then								
								echo $DH_GPU_K_Y | pbcopy
								
				  elif [  "$2" == "pc" ]
							then
								echo $DH_GPU_PC_Y | pbcopy
								
					else 
				  		echo "Nope, not a sub..."
				  		exit 33
				  fi
		 
		elif [  "$1" == "ult" ]
	  		then
					if [  "$2" == "k" ]
				  		then								
								echo $DH_ULT_K_Y | pbcopy
								
				  elif [  "$2" == "pc" ]
							then
								echo $DH_ULT_PC_Y | pbcopy
								
					else 
				  		echo "Nope, not a sub..."
				  		exit 44
				  fi


		elif [  "$1" == "east" ]
	  		then
					if [  "$2" == "k" ]
				  		then								
								echo $DH_EAST_K_Y | pbcopy
								
				  elif [  "$2" == "pc" ]
							then
								echo $DH_EAST_PC_Y | pbcopy
								
					else 
				  		echo "Nope, not a sub..."
				  		exit 55
				  fi	  		

	  else
	  		echo "Nope, not an enviro..."
	  		exit 66
	  fi
		 

		# DH_GPU_K_Y
		# DH_GPU_PC_Y
			
		#returnValue="DH_${enviro}_${evalue}_Y"

		#echo "returnValue: $returnValue"  	
  	
  	#returnValue2="\$$returnValue"
  	
		#echo "returnValue2: $returnValue2"
  	
  	# Actually gets the proper value...but tries to execute it  	
  	#eval "$returnValue2"
  	
	  exit 0

