#!/bin/bash
# Command to full-cycle git

# set -x

usage(){
   			echo " "
   			echo " "
   			echo "Runs Full-Cycle git-sequence.  Be Careful!"
   			echo " "
   			echo " "

   			echo "Usage:   $0 Comments As Args"
   			echo " "
   			echo " "
   			echo " "
	exit 1
}   
  
	if [ $# -lt 1 ] 
		then
			usage
			exit 1
	fi

	commitCommentLine=""
	
	for i do
	    commitCommentLine="$commitCommentLine $i"
  		# echo "Arg: $i"
  		# echo "$commitCommentLine"
	done
	
	clear
	
	git status
	
	## Needed the --all to handle deleted directories as well...
	git add .
	
	git commit -m "$commitCommentLine"
	
  git push
	