#!/bin/bash
#  Call an awk on gradle properties for app version  -OOHHHGAWD!!  Equiv to mvn validate
#

#set -x

usage(){
        echo " "
        echo " "
        echo "Gradle properties | awk ...."
        echo " "
        echo " "

        echo "Usage:   $0 x,y,z "
        echo " "
        echo " "
        echo " "
  exit 1
}   

case $1 in

    -help)
        usage
        ;;
    --help)
        usage
        ;;

    -h)
        usage
        ;;
        
    -H)
        usage
        ;;

    --h)
        usage
        ;;
        
    --H)
        usage
        ;;

esac  


gradle properties -q | awk '/^version:/ {print $2}'


