#!/bin/bash
#
#  Wrapper for gradlew
#

# set -x

usage(){
        echo " "
        echo " "
        echo "Gradle Wrapper"
        echo " "
        echo " "

        echo "Usage:   $0 x,y,z  "
        echo " "
        echo " "
        echo " "
  exit 1
}   

case $1 in

    -help)
        usage
        ;;
    --help)
        usage
        ;;

    -h)
        usage
        ;;
        
    -H)
        usage
        ;;

    --h)
        usage
        ;;
        
    --H)
        usage
        ;;

esac  

if [ $# -gt 0 ]
then

  ./gradlew "$@"

else
  usage

fi 


