#!/bin/bash
#  Call gradle's bootRun
#

#set -x

usage(){
        echo " "
        echo " "
        echo "Gradle bootRun"
        echo " "
        echo " "

        echo "Usage:   $0 x,y,z "
        echo " "
        echo " "
        echo " "
  exit 1
}   

case $1 in

    -help)
        usage
        ;;
    --help)
        usage
        ;;

    -h)
        usage
        ;;
        
    -H)
        usage
        ;;

    --h)
        usage
        ;;
        
    --H)
        usage
        ;;

esac  


./gradlew bootRun "$@"

