#!/bin/bash

#set -x

targetNameSpace=
targetNameSpace="default"

targetNameFragment=
targetNameFragment=""

sinceDuration=
sinceDuration=""

i=0
k=0

usage(){
   			echo " "
   			echo " "
   			echo " "
   			echo "Usage:   $0		-Grabs All Services & Describes for a given Namespace"
   			echo " "
   			echo " -H/-h        -Display this help message."
   			echo " -n           -TargetNameSpace    -Optional. Default: default"
   			echo " -f           -TargetNameFragment -Optional. Default: blank -->all services."   			
   			
   			echo " "
   			echo " Example:   $0 -n targetNameSpace                 # Describes ALL Services in targetNameSpace"  			
   			echo " "
   			echo " Example:   $0 -n targetNameSpace -f prometheus   # Describes Services that contain prometheus in the name ONLY."   			
   			echo " "   			
   			echo " "
   			echo " "   			
	exit 1
}

arg_parse() {
	
	for (( i=1; i<=$#; i++)); do
		
		case ${!i} in
				 	
		  -n)
		  		# targetNameSpace after  -n
		  	  k=$(($i+1))
				 	targetNameSpace="${!k}"
				 	;;
	
			-s)
		  		# sinceDuration after  -s
		  	  k=$(($i+1))
				 	sinceDuration="${!k}"
				 	;;
				 	
			-f)
		  		# targetNameFragment after  -f
		  	  k=$(($i+1))
				 	targetNameFragment="${!k}"
				 	;;				 	
	
	    -H)
					usage
					exit 3
	        ;;
	
	    -h)
					usage
					exit 3
					;;
	
	    --H)
					usage
					exit 3
	        ;;
	
	    --h)
					usage
					exit 3
					;;
	
	    -help)
					usage
					exit 3
	        ;;
	
	    --help)
					usage
					exit 3
					;;
			
			*)
					#echo "[$i]: ${!i}"
		
		
		esac
	
	  
	done

}

dump_services() {

	theCommand=""

	for service in $(kubectl get service -n $targetNameSpace -o jsonpath='{.items[*].metadata.name}'); do 
	    
			if [[ -z "$targetNameFragment" ]]; then

			    echo "=== Describe For Service: $service BEGINS ==="
			    
			    theCommand=""
			    theCommand="kubectl -n $targetNameSpace describe service $service"
			    
			    #echo "theCommand: $theCommand"
			    
			    # Run IT!
			    $theCommand			
			    
					echo "=== Describe For Service: $service ENDS   ==="

			else

				if [[ $service =~ "$targetNameFragment" ]]; then
				
				    echo "=== Describe For Service: $service BEGINS ==="
				    
				    theCommand=""
				    theCommand="kubectl -n $targetNameSpace describe service $service"
				    
				    #echo "theCommand: $theCommand"
				    
				    # Run IT!
				    $theCommand			
				    
						echo "=== Describe For Service: $service ENDS   ==="
									

				fi			

			fi	
			
	done

}

	arg_parse "$@"

	echo " "
	echo "         Target NameSpace: $targetNameSpace"
	echo " "	
	echo "Target TargetNameFragment: $targetNameFragment"
	echo " "	

	dump_services 
	
	exit 0
	
	