#!/bin/bash

#set -x

targetNameSpace=
targetNameSpace="default"

targetNameFragment=
targetNameFragment=""

i=0
k=0

usage(){
   			echo " "
   			echo " "
   			echo " "
   			echo "Usage:   $0		-Grabs All Pods & Describes for a given Namespace"
   			echo " "
   			echo " -H/-h        -Display this help message."
   			echo " -n           -TargetNameSpace -Optional. Default: default"
   			echo " -f           -TargetNameFragment -Optional. Default: blank -->all pods."   			   			
   			echo " "
   			echo " Example:   $0 -n targetNameSpace                 # Describes ALL Pods in targetNameSpace"  			
   			echo " "
   			echo " Example:   $0 -n targetNameSpace -f prometheus   # Describes Pods that contain prometheus in the name ONLY."   			   			
   			echo " "
   			echo " Example:   $0 -n targetNameSpace"
   			echo " "   			
   			echo " "
   			echo " "   			
	exit 1
}

arg_parse() {
	
	for (( i=1; i<=$#; i++)); do
		
		case ${!i} in
				 	
		  -n)
		  		# targetNameSpace after  -n
		  	  k=$(($i+1))
				 	targetNameSpace="${!k}"
				 	;;
	
			-s)
		  		# sinceDuration after  -s
		  	  k=$(($i+1))
				 	sinceDuration="${!k}"
				 	;;
				 	
			-f)
		  		# targetNameFragment after  -f
		  	  k=$(($i+1))
				 	targetNameFragment="${!k}"
				 	;;				 	
				 	
	
	    -H)
					usage
					exit 3
	        ;;
	
	    -h)
					usage
					exit 3
					;;
	
	    --H)
					usage
					exit 3
	        ;;
	
	    --h)
					usage
					exit 3
					;;
	
	    -help)
					usage
					exit 3
	        ;;
	
	    --help)
					usage
					exit 3
					;;
			
			*)
					#echo "[$i]: ${!i}"
		
		
		esac
	
	  
	done

}

dump_podz() {

	theCommand=""

	for pod in $(kubectl get pods -n $targetNameSpace -o jsonpath='{.items[*].metadata.name}'); do 
	    
	    
			if [[ -z "$targetNameFragment" ]]; then	    
	    
			    echo "=== Describe For Pod: $pod BEGINS ==="
			    
			    theCommand=""
			    theCommand="kubectl -n $targetNameSpace describe pod $pod"
			    
			    #echo "theCommand: $theCommand"
			    
			    # Run IT!
			    $theCommand			
			    
					echo "=== Describe For Pod: $pod ENDS   ==="
			
			else

				if [[ $pod =~ "$targetNameFragment" ]]; then
				
				    echo "=== Describe For Pod: $pod BEGINS ==="
				    
				    theCommand=""
				    theCommand="kubectl -n $targetNameSpace describe pod $pod"
				    
				    #echo "theCommand: $theCommand"
				    
				    # Run IT!
				    $theCommand			
				    
						echo "=== Describe For Pod: $pod ENDS   ==="				
				
				fi			
			
			fi	
			
	done


}

	arg_parse "$@"

	echo " "
	echo "Target NameSpace: $targetNameSpace"
	echo " "	
	echo " "	
	echo "Target TargetNameFragment: $targetNameFragment"
	echo " "	


	dump_podz 
	
	exit 0
	
	