#!/bin/bash

#set -x

targetNameSpace=
targetNameSpace=""

sinceDuration=
sinceDuration=""

i=0
k=0

usage(){
   			echo " "
   			echo " "
   			echo " "
   			echo "Usage:   $0		-Grabs All Services & Describes for a given Namespace"
   			echo " "
   			echo " -H/-h        -Display this help message."
   			echo " -n           -TargetNameSpace -REQUIRED"
   			echo " "
   			echo " Example:   $0 -n targetNameSpace"
   			echo " "   			
   			echo " "
   			echo " "   			
	exit 1
}

arg_parse() {
	
	for (( i=1; i<=$#; i++)); do
		
		case ${!i} in
				 	
		  -n)
		  		# targetNameSpace after  -n
		  	  k=$(($i+1))
				 	targetNameSpace="${!k}"
				 	;;
	
			-s)
		  		# sinceDuration after  -s
		  	  k=$(($i+1))
				 	sinceDuration="${!k}"
				 	;;
	
	    -H)
					usage
					exit 3
	        ;;
	
	    -h)
					usage
					exit 3
					;;
	
	    --H)
					usage
					exit 3
	        ;;
	
	    --h)
					usage
					exit 3
					;;
	
	    -help)
					usage
					exit 3
	        ;;
	
	    --help)
					usage
					exit 3
					;;
			
			*)
					#echo "[$i]: ${!i}"
		
		
		esac
	
	  
	done

}

dump_logz() {

	theCommand=""

	for service in $(kubectl get service -n $targetNameSpace -o jsonpath='{.items[*].metadata.name}'); do 
	    
	    echo "=== Describe For Service: $pod BEGINS ==="
	    
	    theCommand=""
	    theCommand="kubectl -n $targetNameSpace describe service $service"
	    
	    #echo "theCommand: $theCommand"
	    
	    # Run IT!
	    $theCommand			
	    
			echo "=== Describe For Service: $pod ENDS   ==="
			
	done

}

	arg_parse "$@"

	echo " "
	echo "Target NameSpace: $targetNameSpace"
	echo " "	

	dump_logz 
	
	exit 0
	
	