#!/bin/bash

#set -x

targetNameSpace=
targetNameSpace="default"

sinceDuration=
sinceDuration="2m"

i=0
k=0

usage(){
   			echo " "
   			echo " "
   			echo " "
   			echo "Usage:   $0		-Grabs & Outputs ALL Pod-Logs for a given Namespace"
   			echo " "
   			echo " -H/-h        -Display this help message."
   			echo " -n           -TargetNameSpace -Optional. Default: default"
   			echo " -s           -SinceDuration, as time duration, (ie 6m for last 6 minutes). -Optional.  Default: 2m"
   			echo " "
   			echo " Example:   $0 -n targetNameSpace"
   			echo " "   			
   			echo " Example:   $0 -n targetNameSpace -s 10m"
   			echo " "
   			echo " "   			
	exit 1
}

arg_parse() {
	
	for (( i=1; i<=$#; i++)); do
		
		case ${!i} in
				 	
		  -n)
		  		# targetNameSpace after  -n
		  	  k=$(($i+1))
				 	targetNameSpace="${!k}"
				 	;;
	
			-s)
		  		# sinceDuration after  -s
		  	  k=$(($i+1))
				 	sinceDuration="${!k}"
				 	;;
	
	    -H)
					usage
					exit 3
	        ;;
	
	    -h)
					usage
					exit 3
					;;
	
	    --H)
					usage
					exit 3
	        ;;
	
	    --h)
					usage
					exit 3
					;;
	
	    -help)
					usage
					exit 3
	        ;;
	
	    --help)
					usage
					exit 3
					;;
			
			*)
					#echo "[$i]: ${!i}"
		
		
		esac
	
	  
	done

}

dump_logz() {

	theCommand=""

	for pod in $(kubectl get pods -n $targetNameSpace -o jsonpath='{.items[*].metadata.name}'); do 
	    
	    echo "=== Logs For Pod: $pod BEGINS ==="
	    
	    theCommand=""
	    theCommand="kubectl logs -n $targetNameSpace $pod --all-containers=true "

			if [[ ! -z "$sinceDuration" ]]; then
				#theCommand="kubectl logs -n $targetNameSpace $pod --all-containers=true --since $sinceDuration "
				theCommand="$theCommand --since $sinceDuration "				
			fi
	    
	    #echo "theCommand: $theCommand"
	    
	    # Run IT!
	    $theCommand			
	    
			echo "=== Logs For Pod: $pod ENDS   ==="
			
	done

}

	arg_parse "$@"

	echo " "
	echo "Target NameSpace: $targetNameSpace"
	echo "  Since Duration: $sinceDuration"	
	echo " "	

	dump_logz 
	
	exit 0
	
	