#!/bin/bash
# Removes current install of docker on ubuntu.
#

#set -x

usage(){
   			echo " "
   			echo " "
   			echo " "
   			echo "Usage:   $0 -F  # -Force flag.  Needed to confirm.  RUN AS ROOT!"
   			echo " "
   			echo " "
   			echo "  Example:"
   			echo "     $0  -F Removes Docker from this machine.... ARE YOU SURE?!?!?!"
   			echo " "
   			echo " "
	exit 1
}


 	if [ $# -lt 1 ]
 		then
			usage
 	fi
   	
	if [ "$1" == "--help" ] || [  "$1" == "--H" ] || [ "$1" == "--h" ] || [  "$1" == "-H" ] || [ "$1" == "-h" ]
	  then
	    usage
	    
	  else
	  	
	  	if [ "$1" != "-F" ]
	  		then 
	  			usage
	  				  	
	  fi	    
	    
	fi
 	
 	echo " "
 	echo "Removing Docker Install...." 	
 	echo " " 	

	set -x

	# Stop Docker service
	systemctl stop docker.socket
	systemctl stop docker
	systemctl disable docker
	
	# Remove core packages (adjust for Desktop/Engine/Snap)
	apt-get purge -y docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-desktop
	apt-get autoremove -y --purge 
	
	# If installed via Snap, use:
	# sudo snap remove docker --purge
	
	
	# Remove all Docker data (images, containers, volumes, networks)
	rm -rfv /var/lib/docker
	rm -rfv /var/lib/containerd
	
	# Remove user-specific configurations
	rm -rfv ~/.docker
	rm -rfv ~/.config/docker
	
	# Remove cli
	rm /usr/bin/docker
	
	# Remove Docker's configuration files
	rm -rfv /etc/docker
	
	# Remove AppArmor profiles (if used)
	rm /etc/apparmor.d/docker
	
	# Remove the docker group (optional)
	#sudo groupdel docker

 	echo " "
 	echo "Docker Removed SUCCESSFULLY!!!" 	 	
 	echo " " 	
 	echo "Strongly Suggest Restart...." 	
 	echo " " 	








