#!/bin/bash
# Runs export of a target kube config file.
#

#set -x

usage(){
   			echo " "
   			echo " "
   			echo " "
   			echo "Usage:   $0 [ target-kube-config file.  .YAML or what-ever."
   			echo " "
   			echo " "
   			echo " "
	exit 1
}


 	if [ $# -lt 1 ]
 		then
			usage
 	fi
   	
	if [ "$1" == "--help" ] || [  "$1" == "--H" ] || [ "$1" == "--h" ] || [  "$1" == "-H" ] || [ "$1" == "-h" ]
	  then
	    usage
	fi
 
  targetConfig=""
  targetConfig="$PWD/$1"
 
 	echo ""
 	echo "Setting KUBECONFIG=$targetConfig"
 	echo ""
 
  unset KUBECONFIG
	export KUBECONFIG="$targetConfig"




