#!/bin/bash
#
#  Wrapper for mvn
#

# set -x

usage(){
        echo " "
        echo " "
        echo "Maven Wrapper"
        echo " "
        echo " "

        echo "Usage:   $0 x,y,z  "
        echo " "
        echo " "
        echo " "
  exit 1
}   

case $1 in

    -help)
        usage
        ;;
    --help)
        usage
        ;;

    -h)
        usage
        ;;
        
    -H)
        usage
        ;;

    --h)
        usage
        ;;
        
    --H)
        usage
        ;;

esac  

if [ $# -gt 0 ]
  then
  	export M2_GLOBAL=
  	export M2_USER=
  	
  	export M2_GLOBAL="${M2_HOME}/conf/settings.xml"
  	export M2_USER="${M2_DATA}/eric/settings.xml"

  	mvn -gs ${M2_GLOBAL} -s ${M2_USER} -DHOME=$HOME "$@"

else
  usage

fi

