#!/bin/bash
#  Set path to java 11.20.3.1
#
echo "Setting Java TO Graal-jdk11.20.3.1........."
export JAVA_HOME=
export JAVA_HOME='/Library/Java/JavaVirtualMachines/graalvm-ce-lts-java11-20.3.1/Contents/Home'

export PATH="${JAVA_HOME}/bin:${PATH}"
