#!/bin/bash
#  Set path to java 11.0.11
#
echo "Setting Java TO jdk11.0.11........."
export JAVA_HOME=
export JAVA_HOME='/Library/Java/JavaVirtualMachines/jdk-11.0.11.jdk/Contents/Home'

export PATH="${JAVA_HOME}/bin:${PATH}"
