#!/bin/bash
#  Set path to graalvm-jdk-17.0.7+8.1
#
echo "Setting Java TO graalvm-jdk-17.0.7+8.1........."
export JAVA_HOME=

export JAVA_HOME='/Library/Java/JavaVirtualMachines/graalvm-jdk-17.0.7+8.1/Contents/Home'

export PATH="${JAVA_HOME}/bin:${PATH}"

