#!/bin/bash
#
# Command launch vsCode (aka ./code w/current dir passed in)
#
#set -x

# UBU-os
targetApp=
targetApp='code '

# UBU-os
launchCommand=
launchCommand=$targetApp

i=0
k=0

usage(){
   			echo " "
   			echo " "
   			echo "Launch vsCode and load current folder as working-folder."
   			echo " "
   			echo " "

   			echo "Usage:   $0 "
   			echo " "
   			echo " "
   			echo " "
	exit 1
}


arg_parse() {
	
	for (( i=1; i<=$#; i++)); do
	
	
		case ${!i} in
		
		  -f)
		  		# File name should follow the -f flag
		  	  k=$(($i+1))
				 	targetLoadFile="${!k}"
				 	break
				 	;;		
	
	    -H)
					usage
					exit 3
	        ;;
	
	    -h)
					usage
					exit 3
					;;
	
	    --H)
					usage
					exit 3
	        ;;
	
	    --h)
					usage
					exit 3
					;;
	
	    -help)
					usage
					exit 3
	        ;;
	
	    --help)
					usage
					exit 3
					;;
			
			*)
					#echo "[$i]: ${!i}"
		
		
		esac
	
	  
	done

}

launch_code() {

	launchCommand="$launchCommand $currentFolder"

	$launchCommand &

}

	arg_parse "$@"

	currentFolder=""
	currentFolder="$PWD"

	echo ""
  echo "In Folder: $currentFolder...."
	echo ""

	launch_code
	
	exit 0
